"use strict";

export const LOAD_BEER_DIRECTORY_SUCCESS = "LOAD_BEER_DIRECTORY_SUCCESS";
export const FETCH_STYLE_CONTENTS_SUCCESS = "FETCH_STYLE_CONTENTS_SUCCESS";
export const FETCH_BEER_DATA_SUCCESS = "FETCH_BEER_DATA_SUCCESS";
