"use strict";

export const LOAD_BEER_DIRECTORY_SUCCESS = "LOAD_BEER_DIRECTORY_SUCCESS";
export const FETCH_STYLE_CONTENTS_SUCCESS = "FETCH_STYLE_CONTENTS_SUCCESS";
export const FETCH_BEER_DATA_SUCCESS = "FETCH_BEER_DATA_SUCCESS";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const SET_CURRENT_BEER = "SET_CURRENT_BEER";
